spring:
  application:
    name: business-control-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/business-control}
    username: ${DATABASE_USERNAME:username}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    show-sql: true